#!/bin/bash
#
# Startup script for yowsup
# 
# chkconfig: 345 80 10
# description: Yowsup whatsapp command server
# processname: yowsup
# pidfile: /var/run/yowsup/yowsup.pid
# source function library

######################################
# CONFIGURATION
######################################

FOLDER=/usr/share/yowsup-commandserver
CONFIG_FILE=yowsup.config
PID_FILE=/var/run/yowsup/yowsup.pid
WAIT_BEFORE_KILL=30

######################################
# START OF THE SCRIPT
######################################

start()
{
	echo "Starting yowsup..."
	echo "------------------------------"
	/usr/bin/python ${FOLDER}/yowsup-cli demos --config ${FOLDER}/${CONFIG_FILE} --commandserver 
	echo ""
}

stop()
{
	echo "Stopping yowsup..."
	echo "------------------------------"
	forceStop;
	echo ""
}

forceStop() 
{
   SLEEP=$WAIT_BEFORE_KILL
   if [ -r "$PID_FILE" ]; then
	echo "Waiting for process: " `cat $PID_FILE`
	while [ $SLEEP -gt 0 ]; do
		sleep 1;
		SLEEP=`expr $SLEEP - 1 `
		
		if [ ! -r "$PID_FILE" ]; then
			echo "Process exited normally."
			break;
		fi
		
		if [ $SLEEP -eq 0 ]; then
			kill -9 `cat $PID_FILE` 2>/dev/null
			rm -f ${PID_FILE} 
			echo "Process killed."
		fi
	done
   fi
}

      
case $1 in  
   start)  
	start
	;;   
   stop)     
	stop
	;;   
   restart)  
	stop
	start
	;;   
   *)
	echo "Unknown option: $1"
	;;
esac   

exit 0  

